name: Get latest release from template
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'
jobs:
  update:
    uses: ObsidianPublisher/actions/.github/workflows/update.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
